name: 'Compare Semvers'
description: 'Compares two semantic versions'
inputs:
  first:  # id of input
    description: 'a semantic version'
    required: true
  second: # id of input
    description: 'another semantic version'
    required: true
  op:
    description: '< | > | <= | =>'
    required: false
outputs:
  result: # output will be available to future steps
    description: 'If op is present, will be true or false; else will be -1, 0, or 1'
runs:
  using: 'node16'
  main: 'dist/index.js'
